#! /bin/bash

### BEGIN INIT INFO
# Provides:          rshutdown
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rshutdown service
# Description:       Run rshutdown service
### END INIT INFO


NAME="rshutdown"

DAEMON="/usr/bin/rshutdown"
DAEMON_USER="rshutdown"
DAEMON_PID="/run/${NAME}.pid"
DAEMON_LOG="/var/log/${NAME}/${NAME}.log"

DEFAULT="/etc/default/${NAME}"

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

# configure daemon
RSHUTDOWN_TOKEN=
RSHUTDOWN_HTTP_PORT=

if [ -f "${DEFAULT}" ]; then
    . "${DEFAULT}"
fi

DAEMON_ENV_VARS="RSHUTDOWN_TOKEN=${RSHUTDOWN_TOKEN} RSHUTDOWN_HTTP_PORT=${RSHUTDOWN_HTTP_PORT}"

test -x ${DAEMON} || exit 0

. /lib/lsb/init-functions

# start daemon
d_start () {
    log_daemon_msg "Starting system ${NAME} Daemon"
    start-stop-daemon --start --background --pidfile ${DAEMON_PID} --make-pidfile \
     --chuid ${DAEMON_USER} --startas /bin/bash -- -c "exec /usr/bin/env ${DAEMON_ENV_VARS} ${DAEMON} >> ${DAEMON_LOG} 2>&1"
    log_end_msg $?
}

# stop daemon
d_stop () {
    log_daemon_msg "Stopping system ${NAME} Daemon"
    start-stop-daemon --stop --pidfile ${DAEMON_PID} --retry 5  --remove-pidfile
    log_end_msg $?
}

# main
case "$1" in

    start|stop)
        d_${1}
        ;;

    restart|reload|force-reload)
        d_stop
        d_start
        ;;

    *)
        echo "Usage: /etc/init.d/${NAME} {start|stop|restart|reload|force-reload}"
        exit 1
        ;;
esac
exit 0
